name: bash_unit CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Unit testing with bash_unit
      run: ./entrypoint.sh tests

  macos:
    runs-on: macos-latest
    if: "contains(toJSON(github.event.commits.*.message), '[macos]')"

    steps:
    - uses: actions/checkout@v2

    - name: Unit testing with bash_unit
      run: ./entrypoint.sh tests
